#list
list=["name",456,"ssas"]
print(type(list))
print(list)
#tuples
tuples=("Name","da")
print(tuples)
print(type(tuples))
#dictionaries
student={"Name":"sun","Subject":"BDA","Age":100}
print(type(student))
print(student)
#set
sd={"334",43,545}
print(type(sd))