'''print("name :")
name =input()
print("enter course :")
subject =input()
print("enter father  name :")
fname=input()
print("Date of birth :")
dob=input()
print("enter marks :")
print("english :")
eng =int(input())
print("computer :")
comp=int(input())
print("math :")
math=int(input())
print("science :")
science=int(input())
print("\n\t\t\t\t\tmarksheet")
print("name",name)
print("father name",fname)
print("date of birth",dob)

print("\n\t\t\t\t\t\tmarks obtained")
print("\nenglish :\t",eng)
print("\ncomputer :\t" ,comp)
print("\nmath :\t\t",math)
print("\nscience :\t`",science)'''
print(input(""))
print ("error")

